name: Publish Tiny Art to tinyart.github.io

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - run: npm install
    - run: npm run compile
    - run: npm run build
      env:
        CI: true
